name: Validate JSONs on PR
on: [pull_request]
jobs:
  validate_schemas:
    name: Validate JSON Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate People JSON schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ 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 }}
          json_path_pattern: ^translations/.+\.json$
          send_comment: true
          clear_comments: true
